name: Conviso Platform AST
on:
 workflow_dispatch:
 #push:
 #  branches: [ main, develop ]
 #pull_request:
 #  branches: [ main, develop ]

jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    container:
      image: convisoappsec/convisocli:latest
      env:
        ASSET_NAME: 'guzzle-new'
        CONVISO_API_KEY: ${{secrets.CONVISO_API_KEY}}
    steps:
    - uses: actions/checkout@v4
  
    - name: AST
      run: conviso ast run
